require: rubocop-rspec

AllCops:
  Exclude:
    - bin/*
    - poms.gemspec

Style/Documentation:
  Exclude:
    - 'lib/poms/has_ancestors.rb'
    - spec/**/*_spec.rb

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*.rb'

Style/AndOr:
  Exclude:
    - 'lib/poms.rb' # here we do rely on how `or` has lower precedence than `||`
    - 'lib/poms/configuration.rb' # here we do rely on how `or` has lower precedence than `||`

Metrics/LineLength:
  Max: 90
