require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - bin/*
    - poms.gemspec

Style/Documentation:
  Exclude:
    - 'lib/poms/has_ancestors.rb'
    - spec/**/*_spec.rb

Style/ModuleFunction:
  Exclude:
    - 'lib/poms.rb'
    - 'lib/poms/fields.rb'
    - 'lib/poms/merged_series.rb'
    - 'lib/poms/views.rb'
