require: rubocop-rspec

inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - bin/*
    - poms.gemspec
    - vendor/**/*

Style/Documentation:
  Exclude:
    - 'lib/poms/has_ancestors.rb'
    - spec/**/*_spec.rb

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/AndOr:
  Exclude:
    - 'lib/poms.rb' # here we do rely on how `or` has lower precedence than `||`
    - 'lib/poms/configuration.rb' # here we do rely on how `or` has lower precedence than `||`

Style/FrozenStringLiteralComment:
  Enabled: false

ModuleLength:
  Exclude:
    - spec/**/*_spec.rb # specs are only in module for easier access to functions

RSpec/ExampleLength:
  Max: 15

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
